---
spring:
  main:
    web-environment: false
logging:
  pattern:
    console:

fx:
  calculator:
    reg-exp:
      input: (^[A-Z a-z]{3}[\s]{1,4}[0-9]+(\.[0-9]{1,2})*[\s]{1,4}[IN in]{2}[\s]{1,4}([A-Z a-z]{3}$))
    main-conversion-table: AUD/USD=0.8371,CAD/USD=0.8711,USD/CNY=6.1715,EUR/USD=1.2315,GBP/USD=1.5683,NZD/USD=0.7750,USD/JPY=119.95,EUR/CZK=27.6028,EUR/DKK=7.4405,EUR/NOK=8.6651
    aud-cross-conversion-table: AUD/CAD=USD,AUD/CNY=USD,AUD/CZK=USD,AUD/DKK=USD,AUR/EUR=USD,AUD/GBP=USD,AUD/JPY=USD,AUD/NOK=USD,AUD/NZD=USD
    default-decimal-point: 2
    special-decimal-point: JPY=0
  message:
    welcome: Welcome to FX Calculator.
    format-info: HELP   .... Data Format .... <Source Currency> <amount>  <In> <Target Currency> format e.g. AUD 100.00 in USD
    enter-input: Please enter your input
    invalid-input: Sorry .... Invalid input format . Please try again..
    input-delimiter: \s
    continue-option-msg: Do you want to continue ? (Y/N)
    no-msg: N
    key-separator: /
    key-value-seprator: =
    comma-separator: ','
