---
spring:
  main:
    web-environment: false
logging:
  pattern:
   console:

fx:
  calculator:
    console:
      true
    reg-exp:
      input: (^[A-Z a-z]{3}[\s]{1,4}[0-9]+(\.[0-9]{1,2})*[\s]{1,4}[IN in]{2}[\s]{1,4}([A-Z a-z]{3}$))

    main-conversion-table: AUD/USD=0.8371,CAD/USD=0.8711,USD/CNY=6.1715,EUR/USD=1.2315,GBP/USD=1.5683,NZD/USD=0.7750,USD/JPY=119.95,EUR/CZK=27.6028,EUR/DKK=7.4405,EUR/NOK=8.6651

    aud-cross-conversion-table: AUD/CAD=USD,AUD/CNY=USD,AUD/CZK=USD,AUD/DKK=USD,AUR/EUR=USD,AUD/GBP=USD,AUD/JPY=USD,AUD/NOK=USD,AUD/NZD=USD
    cad-cross-conversion-table: CAD/AUD=USD,CAD/CNY=USD,CAD/CZK=USD,CAD/DKK=USD,CAD/EUR=USD,CAD/GBP=USD,CAD/JPY=USD,CAD/NOK=USD,CAD/NZD=USD
    cny-cross-conversion-table: CNY/AUD=USD,CNY/CAD=USD,CNY/CZK=USD,CNY/DKK=USD,CNY/EUR=USD,CNY/GBP=USD,CNY/JPY=USD,CNY/NOK=USD,CNY/NDZ=USD
    czk-cross-conversion-table: CZK/AUD=USD,CZK/CAD=USD,CZK/CNY=USD,CZK/DKK=USD,CZY/GBP=USD,CZY/JPY=USD,CZK/NOK=USD,CZK/NDZ=USD,CZK/USD=EUR
    dkk-cross-conversion-table: DKK/AUD=USD,DKK/CAD=USD,DKK/CNY=USD,DKK/CZK=EUR,DKK/GBP=USD,DKK/JPY=USD,DKK/NOK=EUR,DKK/NDZ=USD,DKK/USD=EUR
    eur-cross-conversion-table: EUR/AUD=USD,EUR/CAD=USD,EUR/CNY=USD,EUR/GBP=USD,EUR/JPY=USD,EUR/NDZ=USD
    gbp-cross-conversion-table: GBP/AUD=USD,GBP/CAD=USD,GBP/CNY=USD,GBP/CZK=EUR,GBP/DKK=USD,GBP/EUR=USD,GBP/JPY=USD,GBP/NOK=USD,GBP/NZD=USD
    jpy-cross-conversion-table: JPY/AUD=USD,JPY/CAD=USD,JPY/CNY=USD,JPY/CZK=EUR,JPY/DKK=USD,JPY/EUR=USD,JPY/GBP=USD,JPY/NOK=USD,JPY/NZD=USD
    nok-cross-conversion-table: NOK/AUD=USD,NOK/CAD=USD,NOK/CNY=USD,NOK/CZK=EUR,NOK/DKK=EUR,NOK/GBP=USD,NOK/JPY=USD,NOK/NZD=USD,NOK/USD=EUR
    nzd-cross-conversion-table: NZD/AUD=USD,NZD/CAD=USD,NZD/CNY=USD,NZD/CZK=USD,NZD/DKK=USD,NZD/EUR=USD,NZD/GBP=USD,NZD/NOK=USD
    usd-cross-conversion-table: USD/CZK=EUR,USD/DKK=EUR,USD/NOK=EUR

    default-decimal-point: 2
    special-decimal-point: JPY=0
    conversion-rate-decimal-point: 4
  message:
    welcome: Welcome to FX Calculator.
    format-info: HELP   .... Data Format .... <Source Currency> <amount>  <In> <Target Currency> format e.g. AUD 100.00 in USD
    enter-input: Please enter your input
    invalid-input: Sorry .... Invalid input format . Please try again..
    input-delimiter: \s
    continue-option-msg: Do you want to continue ? (Y/N)
    no-msg: N
    key-separator: /
    key-value-seprator: =
    currency-pair-separator: ','

